---
shared:
  timezone: America/New_York
  locales: en_US en_US.UTF-8
  swap_size: 2048M
  ssl_country: CA
  ssl_state: QC
  ssl_city: Quebec
  ssl_organization: TODO

admin:
  reboot: false
  remove_recipes:
  #   - ssl_ca
  #   - ssl_server
    - backup
    - logrotate
  append_recipes:
    - logrotate
    - mysql
    - wkhtmltopdf
