web:
  role_before:
    - web/load_defaults
    - web/git_wrapper
  recipes:
    - deploy/rbenv:
        after: deploy/stage
    - deploy/bundler:
        before: deploy/updated
    - deploy/migrate:
        after: deploy/updated
    - deploy/assets:
        after: deploy/migrate
    - deploy/passenger:
        after: deploy/publish
  linked_dirs:
    - log
    - node_modules
    - public/packs
    - tmp/files
    - tmp/cache
    - tmp/pids
    - tmp/webpacker
