provision:
  recipes:
    - bootstrap/upgrade-{upgrade}
    - bootstrap/time_locale
    - bootstrap/files
    - bootstrap/swap-{swap_size}
    - bootstrap/limits
    - bootstrap/packages
    - bootstrap/ssh
    - bootstrap/firewall
    - bootstrap/firewall/deny_mail
    - bootstrap/fail2ban
    - bootstrap/private_ip
    - bootstrap/osquery
    - bootstrap/clamav
    - user/deployer
    - db/postgres-{postgres}
    - db/postgres-{postgres}/pgxnclient
    - db/postgres-{postgres}/vector:
        if: 'sun.vector_enabled'
    - db/postgres-{postgres}/pg_repack:
        if: 'sun.pgrepack_enabled'
    - nginx/passenger
    - nginx/htpasswd
    - ssl/ca:
        if: 'sun.server_ssl'
    - ssl/self_signed:
        if: 'sun.server_ssl'
    - ssl/dhparam:
        if: 'sun.server_ssl'
    - lang/ruby/system
    - lang/nodejs/system-{nodejs}
    - lang/python/system
    - addons/gis_packages:
        if: 'sun.postgis_enabled'
    - db/postgres-{postgres}/postgis-{postgis}:
        if: 'sun.postgis_enabled'
    - db/postgres-{postgres}/timescaledb:
        if: 'sun.timescaledb_enabled'
    - db/postgres-{postgres}/tune:
        unless: 'sun.timescaledb_enabled'
    - db/postgres-{postgres}/config
    - utils/packages
    - utils/htop
    - utils/mailcatcher:
        if: 'sun.env.vagrant?'
    - utils/parallel
    - lang/ruby/app-{ruby_version}
deploy:
  role_before:
    - deploy/rbenv
    - deploy/rails_env
  recipes:
    - deploy/authorized_keys-system:
        before: deploy/start
    - deploy/logrotate-system:
        before: deploy/update
    - deploy/secrets-system:
        before: deploy/update
    - deploy/private_dns-system:
        before: deploy/update
    - deploy/nginx/config-system:
        before: deploy/update
    - deploy/database-system:
        before: deploy/update
        if: '%w(127.0.0.1 localhost).include? sun.db_host'
    - deploy/bundler:
        after: deploy/update
    - deploy/assets:
        after: deploy/bundler
        if: 'sun.passenger'
    - deploy/migrate:
        before: deploy/updated
    - deploy/nginx/reload-system:
        after: deploy/publish
    - deploy/passenger:
        before: deploy/published
        if: 'sun.passenger'
    - deploy/osquery-system:
        after: deploy/finished
  linked_dirs:
    - log
    - node_modules
    - public/packs
    - tmp/files
    - tmp/cache
    - tmp/pids
    - tmp/webpacker
  linked_files:
    - config/secrets.yml
    - public/503.html
  git_shallow_clone: true
  nginx_satisfy: false
  nginx_auth_basic: false
  nginx_redirects: {}
  public_dirs:
    - css
    - js
  public_files:
    - robots.txt
  osquery_logger_level: 1
  osquery_database_path: /var/osquery/osquery.db
  osquery_day: 86400
  osquery_hour: 3600
  osquery_minute: 60
  osquery_2_hrs: 7200
  osquery_10_min: 600
  osquery_10_sec: 10

deploy_development:
  osquery_logger_level: 0
  osquery_database_path: ./tmp/osquery/osquery.db
  #  osquery_day: 10
  #  osquery_hour: 10
  #  osquery_minute: 10
  #  osquery_2_hrs: 10
  #  osquery_10_min: 10
  #  osquery_10_sec: 10
