web:
  role_before:
    - web/rbenv
    - web/rails_env
  recipes:
    - deploy/authorized_keys-system:
        before: deploy/start
    - deploy/logrotate-system:
        before: deploy/update
    - deploy/secrets-system:
        before: deploy/update
    - deploy/private_dns-system:
        before: deploy/update
    - deploy/nginx/config-system:
        before: deploy/update
    - deploy/database-system:
        before: deploy/update
        if: '%w(127.0.0.1 localhost).include? sun.db_host'
    - deploy/bundler:
        after: deploy/update
    - deploy/assets:
        after: deploy/bundler
    - deploy/migrate:
        before: deploy/updated
    - deploy/nginx/reload-system:
        after: deploy/publish
    - deploy/passenger:
        before: deploy/published
        if: 'sun.passenger'
    - deploy/osquery-system:
        after: deploy/finished
  linked_dirs:
    - log
    - node_modules
    - public/packs
    - tmp/files
    - tmp/cache
    - tmp/pids
    - tmp/webpacker
  linked_files:
    - config/secrets.yml
    - public/503.html
  git_shallow_clone: true
  nginx_satisfy: false
  nginx_auth_basic: false
  nginx_deferred: false
  nginx_redirects: {}
  public_dirs:
    - css
    - js
  public_files:
    - robots.txt
  osquery_logger_level: 1
  osquery_database_path: /var/osquery/osquery.db
  osquery_day: 86400
  osquery_hour: 3600
  osquery_minute: 60
  osquery_2_hrs: 7200
  osquery_10_min: 600
  osquery_10_sec: 10

web_development:
  osquery_logger_level: 0
  osquery_database_path: ./tmp/osquery/osquery.db
  #  osquery_day: 10
  #  osquery_hour: 10
  #  osquery_minute: 10
  #  osquery_2_hrs: 10
  #  osquery_10_min: 10
  #  osquery_10_sec: 10

web_production:
  nginx_deferred: <%= Setting[:passenger] %>
