web:
  role_before:
    - web/load_defaults
    - web/git_wrapper
    - web/rbenv
  recipes:
    - deploy/cron_log-system:
        before: deploy/update
    - deploy/logrotate-system:
        before: deploy/update
    - deploy/secrets-system:
        before: deploy/update
    - deploy/private_dns-system:
        before: deploy/update
    - deploy/nginx/config-system:
        before: deploy/update
    - deploy/database-system:
        before: deploy/update
    - deploy/bundler:
        after: deploy/update
    - deploy/assets:
        after: deploy/bundler
    - deploy/migrate:
        before: deploy/updated
    - deploy/nginx/reload-system:
        after: deploy/publish
    - deploy/passenger:
        before: deploy/published
  linked_dirs:
    - log
    - node_modules
    - public/packs
    - tmp/files
    - tmp/cache
    - tmp/pids
    - tmp/webpacker
  linked_files:
    - config/secrets.yml
  git_config_url: true
  git_shallow_clone: true
  nginx_satisfy: false
  nginx_auth_basic: false
  nginx_deferred: false
  nginx_redirects: {}
  public_dirs:
    - css
    - js
  public_files:
    - robots.txt

web_production:
  nginx_deferred: <%= Setting[:passenger] %>
