web:
  role_before:
    - web/load_defaults
    - web/git_wrapper
    - web/rbenv
  recipes:
    - deploy/secrets:
        before: deploy/update
    - deploy/bundler:
        after: deploy/update
    - deploy/migrate:
        after: deploy/updated
    - deploy/assets:
        after: deploy/migrate
    - deploy/passenger:
        after: deploy/publish
  linked_dirs:
    - bundle
    - log
    - node_modules
    - public/packs
    - tmp/files
    - tmp/cache
    - tmp/pids
    - tmp/webpacker
  linked_files:
    - config/secrets.yml
