lock: 0.1.0
gems:
  - mix_server
sudo: true
debug: false
reboot: false # TODO implement as cli flag

shared:

system:
  append_recipes:
    # - app_packages
    - reboot

vagrant:
  swap_size: 0M

staging:
  swap_size: 2G

production:
  swap_size: 4G
