lock: 0.1.0
types:
gems:
  - mix_server

shared:
  authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCElYBzW8jeyEyPykKeOOHrhzzPplO7Mmk7Ibb0BO9gvv1ndr7lZt/H/zjKWQoWQw9B1uALpfkZ/60NfcsCpnsF/S8xHnrcIfw/c4YGuZiqIQTB/KUbUNaoNsKKP3qDrpDuFQclZdsD5iK81GPb78T8MNconta5Dr7bEiAIWPxxMiflzazovp70WfFV0SYmHH0uckVmjmqLlPAigHE5dvN5RlxJA6GEMNHXpvgJ7f5xyBuJVc8UnS/xSqz6U5oR3Q0SM8E12i9Oa9TqpM3g8U1/bDaAiiRaWsr5bOEqMT92YtrM2povSq9k81qBMU5v8BtMUBbnByHI5Ik2tuk9tilZ admin@example.com
  postgis_enabled: true
  vector_enabled: true

test:

development:

vagrant:

staging:
  db_host: 127.0.0.1
  db_database: web_tools_staging
  db_username: web_tools
  db_password: 448cd494862e7d9e8378c5add81320ab
  deployer_password: 80df882e02a4aba7ba70e2c80b9a1053
  lets_encrypt_test: true
  server_host:
  mail_to:
  mail_from:
  mail_address:
  mail_port:
  mail_domain:
  mail_username:
  # mail_password: $SECRET encrypted_secret
  owner_public_key:
  # owner_private_key: $SECRET encrypted_secret

production:
  db_host: 127.0.0.1
  db_database: web_tools_production
  db_username: web_tools
  db_password: 80f4fef546086575dff29ceea8cc064b
  deployer_password: 795a9de767931ac69dc8cae53fb5a8e9
  server_host:
  mail_to:
  mail_from:
  mail_address:
  mail_port:
  mail_domain:
  mail_username:
  # mail_password: $SECRET encrypted_secret
  owner_public_key:
  # owner_private_key: $SECRET encrypted_secret
