lock: 0.1.0
types:
gems:
  - mix_server

shared:
  authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCElYBzW8jeyEyPykKeOOHrhzzPplO7Mmk7Ibb0BO9gvv1ndr7lZt/H/zjKWQoWQw9B1uALpfkZ/60NfcsCpnsF/S8xHnrcIfw/c4YGuZiqIQTB/KUbUNaoNsKKP3qDrpDuFQclZdsD5iK81GPb78T8MNconta5Dr7bEiAIWPxxMiflzazovp70WfFV0SYmHH0uckVmjmqLlPAigHE5dvN5RlxJA6GEMNHXpvgJ7f5xyBuJVc8UnS/xSqz6U5oR3Q0SM8E12i9Oa9TqpM3g8U1/bDaAiiRaWsr5bOEqMT92YtrM2povSq9k81qBMU5v8BtMUBbnByHI5Ik2tuk9tilZ deployer@example.com
  postgis_enabled: true
  vector_enabled: true

test:

development:

virtual:

staging:
  db_host: 127.0.0.1
  db_database: staging_web_tools
  db_username: staging_web_tools
  db_password: $SECRET +60k5KLqKuVpG4Iv6Lun4TFQbeyrki42N47JjYuBxEvmoNIIiDalV3xb--Uyu7eZU9Qxf3AL9B--yNZ5fovUhHbNaW1j00yygw==
  deployer_password: $SECRET gLF4Wc/KiQyRNYpQkjLsyCI6syOk7BIyIcOKa3gIDmdKmqPNgQr4X4Ow--VKhrY5TgnB3G3JaM--WRKYN1pfNDa6FebpPSALiQ==
  server_host:
  mail_to:
  mail_from:
  mail_address:
  mail_port:
  mail_domain:
  mail_username:
  # mail_password: $SECRET encrypted_secret
  owner_public_key:
  # owner_private_key: $SECRET encrypted_secret

production:
  db_host: 127.0.0.1
  db_database: production_web_tools
  db_username: production_web_tools
  db_password: $SECRET YtffoDUpU9coNeJCOcy1kNFgIws5YRIIq1yFWlsH3Pt7cfDZO1mOKNd5--baxA65Grq/SB62wj--ijzwJ90onfjdguFaJ6bbvw==
  deployer_password: $SECRET tTbqDusnf2eEAtE3TQU7qE+jblKdUh4Y5Lw6ViLnvTPaAjGYfUk9rwL/--FTjht++NLS5KsbIR--Npd45zsd0X8CHUe3Q3uoTQ==
  server_host:
  mail_to:
  mail_from:
  mail_address:
  mail_port:
  mail_domain:
  mail_username:
  # mail_password: $SECRET encrypted_secret
  owner_public_key:
  # owner_private_key: $SECRET encrypted_secret
