lock: 0.1.0
gems:
  - mix_server
  - mix_job
  - ext_whenever

shared:
  debug: false

system:
  recipes:
    # - app_packages
    - reboot

web:
  recipes:
    - deploy/add_gitignored_files:
        before: deploy/bundler
  git_config_url: true

vagrant:
  swap_size: 0

staging:
  swap_size: 2G

production:
  swap_size: 4G
