lock: 0.1.0
gems:
  - mix_server

shared:
  debug: false

system:
  recipes:
    # - app_packages
    - reboot

web:
  recipes:
    - deploy/add_gitignored_files:
        before: deploy/bundler

vagrant:
  swap_size: 0

staging:
  swap_size: 2G

production:
  swap_size: 4G
