lock: 0.1.0
gems:
  - mix_server

shared:
  sudo: true
  debug: false

system:
  append_recipes:
    # - app_packages
    - reboot

vagrant:
  swap_size: 0

staging:
  swap_size: 2G

production:
  swap_size: 4G
