lock: 0.1.0
gems:
  - mix_server
  - mix_job
  - mix_file
  - mix_geo
  - ext_rails
  - ext_whenever

shared:
  debug: false

provision:
  recipes:
    # - app_packages
    - reboot

deploy:
#  recipes:
#    - deploy/add_gitignored_files:
#        before: deploy/bundler
  git_config_url: true

virtual:
  swap_size: 1G

staging:
  swap_size: 2G

production:
  swap_size: 4G
