deploy:
  recipes:
    - deploy/job/config-system:
        before: deploy/published
    - deploy/job/restart:
        before: deploy/published
        if: 'sun.passenger'
  linked_dirs:
    - tmp/jobs
  job_queue: default
