deploy:
  recipes:
    - deploy/whenever/config-system:
        before: deploy/update
    - deploy/whenever/update:
        before: deploy/published
  scripts:
    - whenever/update
    - whenever/clear
  linked_dirs:
    - tmp/locks
