types:
  mail_to: emails
  server_ssl: boolean
  backup_dir: pathname

shared:
  default_url_options: $METHOD
  server: $METHOD
  mail_to: admin@notify.example.com
  mail_from: noreply@notify.example.com
  mail_address: localhost
  mail_port: 1025
  pgstats_enabled: true
  backup_split_size: 4
  backup_dir: /opt/storage/backup

test:
  server_host: localhost
  server_port: 3000
  mail_domain: $ALIAS server
  backup_dir: ./tmp/backup

development:
  server_host: localhost
  server_port: 3000
  mail_domain: $ALIAS server
  backup_dir: ./tmp/backup

vagrant:
  server_ssl: true
  server_host: vagrant-web.test
  mail_domain: notify.vagrant-web.test

staging:

production:
