types:
  mail_to: emails
  server_ssl: boolean

shared:
  default_url_options: $METHOD
  server: $METHOD
  mail_to: admin@notify.example.com
  mail_from: noreply@notify.example.com
  mail_address: localhost
  mail_port: 1025
  db_pg_dump_split_size: 2

test:
  server_host: localhost
  server_port: 3000
  mail_domain: $ALIAS server

development:
  server_host: localhost
  server_port: 3000
  mail_domain: $ALIAS server

vagrant:
  server_ssl: true
  server_host: vagrant-web.test
  mail_domain: notify.vagrant-web.test

staging:

production:
