shared:
  pghero_long_running_query_sec: 60
  pghero_slow_query_ms: 2000
  pghero_slow_query_calls: 10
  pghero_total_connections_threshold: 500
  pghero_explain_timeout_sec: 10
  pghero_time_zone: UTC
