types:
  check_database_interval: interval
  check_host_interval: interval

shared:
  pg_log_min_duration: 2000
  # check_long_running_query_sec: 60
  check_slow_query_ms: $ALIAS pg_log_min_duration
  check_slow_query_calls: 1
  # check_total_connections_threshold: 500
  # check_explain_timeout_sec: 10
  check_time_zone: UTC
  check_filter_data: false
  # check_capture_query_stats: true
  # check_cache_hit_rate_threshold: 99
  # check_index_bloat_bytes: 104857600
  check_table_bloat_factor: 10.0
  check_table_bloat_bytes: 104857600
  check_database_interval: 5 minutes
  check_host_interval: 1 minute
