deploy:
  role_before:
    - deploy/load_defaults
    - deploy/git_wrapper
  role_ensure:
    - deploy/git_cleanup
  scripts:
    - version

virtual:
  vm_cpu: 2
  vm_ram: 1GB
  vm_disk: 10GB

desktop:
